language: go

go:
  - 1.13

before_install:
  - go get -u github.com/kr/pretty
  - go get -u github.com/BurntSushi/ty
  - go get -u github.com/BurntSushi/ty/fun
  - go get -u golang.org/x/tools/go/ast/astutil
  - go get -u golang.org/x/tools/go/packages

script:
  # run tests on a standard platform
  - go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
